"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var auth_1 = require("../middleware/auth");
var userRouter = express_1.default.Router();
userRouter.post('/registration', user_controller_1.registerationUser);
userRouter.post('/activate-user', user_controller_1.activateUser);
userRouter.post('/login', user_controller_1.loginUser);
userRouter.get('/logout', auth_1.isAuthenticated, user_controller_1.logoutUser);
userRouter.get('/refresh-token', user_controller_1.updateAccessToken);
userRouter.get('/me', auth_1.isAuthenticated, user_controller_1.getUserInfo);
userRouter.post('/social-auth', user_controller_1.socialAuth);
userRouter.put('/update-user-info', auth_1.isAuthenticated, user_controller_1.updateUserInfo);
userRouter.put('/update-user-password', auth_1.isAuthenticated, user_controller_1.updatePassword);
userRouter.put('/update-user-avatar', auth_1.isAuthenticated, user_controller_1.updateProfilePicture);
userRouter.get('/get-users', auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), user_controller_1.getAllUsers);
userRouter.put('/update-user-role', auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), user_controller_1.updateUserRole);
userRouter.delete('/delete-user/:id', auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), user_controller_1.deleteUser);
exports.default = userRouter;
